# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Lncosie
description:      ''
url:              http://lncosie.github.io/
baseurl:          /
logo:             /content/images/me.png

author:
  name:           'Lncosie'
  url:            https://github.com/lncosie
  email: 		      lncosie@gmail.com
paginate:         5


disqus_shortname: frank

github:
  repo:           https://github.com/lncosie/lncosie.github.io

# gems:
  # - jekyll-sitemap

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
